# fly.toml app configuration file generated for long-snow-3592 on 2023-11-12T01:02:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "long-snow-3592"
primary_region = "ams"

[build]

[env]
  PORT = 3000

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
